services:
  db:
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --local-infile=1 --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME:-db}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}

volumes:
  db:
